apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-38a0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-38a0@sha256:84e53151b910f5d240991b09827b4a76f14756dd129dcef6d375925d58c48434
        name: my-nodejs
        resources: {}
status: {}
